# Generated by Django 3.0.8 on 2020-07-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_linha', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_parada', models.CharField(default='', max_length=50)),
                ('lat_parada', models.BigIntegerField()),
                ('long_parada', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_veiculo', models.CharField(default='', max_length=30)),
                ('model_veiculo', models.CharField(default='', max_length=30)),
                ('id_linha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Linha')),
            ],
        ),
        migrations.CreateModel(
            name='PosicaoVeiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_veiculo', models.BigIntegerField()),
                ('long_veiculo', models.BigIntegerField()),
                ('id_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ParadasLinha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Linha')),
                ('id_paradas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Paradas')),
            ],
        ),
    ]
