# Generated by Django 3.0.8 on 2020-07-12 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradaslinha',
            old_name='id_linha',
            new_name='linha',
        ),
        migrations.RenameField(
            model_name='paradaslinha',
            old_name='id_paradas',
            new_name='paradas',
        ),
        migrations.RenameField(
            model_name='posicaoveiculos',
            old_name='id_veiculo',
            new_name='veiculo',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='id_linha',
            new_name='linha',
        ),
    ]
