# Generated by Django 3.0.8 on 2020-07-12 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200712_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradaslinha',
            name='linha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Linha'),
        ),
        migrations.AlterField(
            model_name='paradaslinha',
            name='paradas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Paradas'),
        ),
        migrations.AlterField(
            model_name='posicaoveiculos',
            name='veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Veiculo'),
        ),
    ]
