# Generated by Django 3.0.8 on 2020-07-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200714_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paradaslinha',
            name='linha',
        ),
        migrations.AddField(
            model_name='paradaslinha',
            name='linha',
            field=models.ManyToManyField(blank=True, null=True, related_name='linhas', to='api.Linha'),
        ),
    ]
