# Generated by Django 3.0.8 on 2020-07-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200714_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='linha',
            name='paradas',
            field=models.ManyToManyField(blank=True, related_name='linhas', to='api.Paradas'),
        ),
    ]
