# Generated by Django 3.0.8 on 2020-07-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200714_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParadasLinha',
        ),
    ]
