# Generated by Django 3.0.8 on 2020-07-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_paradaslinha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='linha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='api.Linha'),
        ),
    ]
