# Generated by Django 3.0.8 on 2020-07-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200714_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicaoveiculos',
            name='veiculo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posicao', to='api.Veiculo'),
        ),
    ]
