# Generated by Django 3.0.8 on 2020-07-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200714_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicaoveiculos',
            name='id',
        ),
        migrations.AlterField(
            model_name='posicaoveiculos',
            name='veiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='posicao', serialize=False, to='api.Veiculo'),
        ),
    ]
